<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
   
    <link rel="stylesheet" href="../public/css/bootstrap.min.css">
    <link rel="stylesheet" href="style/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="index.phtml">
              <img src="../public/css/img/mask.jpg" width="55" height="55" alt="" loading="lazy">
            </a>
            <a class="navbar-brand" href="index.phtml">CONTAGION</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-link active" href="index.phtml">Home<span class="sr-only">(current)</span></a>
                <a class="nav-link" href="#">Items</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="#">Clothes</a>
                      <a class="dropdown-item" href="#">Shoes</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Electronics</a>
                    </div>
                 </li>
              </div>
            </div>
            <div class="navbar-nav">
            <a class="nav-link " href="loginPage.phtml">Login</a>
          </div>
            <form class="form-inline">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          </form>
          </nav>
    </header>

        <main>
        <div class="container">
          <div class="row">
              <div class="col-md-6 desc">
                <h3>
                    Prices so good,it would make you sick
                </h3>
                <p class="lead"><b>A website that's COVID friendly for every user in the planet. We provide you products only we can offer. All customer checkouts are remotely, so no human contact needed! We've provided different Categories that might take you interest.</b></p>
                <p class="lead">Start Shopping and Welcome to Contagion</p>
                <a class="btn btn-primary btn-lg" href="#" role="button">View Items</a>
              </div>
            <div class="col-md-6">
              <img src="../public/css/img/IMG_4780.jpg" class="rounded mx-auto d-block img-fluid" style="margin-top:28%;" width="450" height="450">
            </div>
          </div>
        </div>

        <h3 class="mt-5 pb-3"style="text-align: center; font-size: 2em;">COVID Stay inside and Be Safe</h3>

        <div class="container mt-5" >
          <div class="row">
            <div class="col-sm">
              <img class="card-img-top" src="../public/css/img/IMG_4781.jpg"  height="300" alt="item2">
              <div class="card-body">
                <h5 class="card-title">Item 1</h5>
                <p class="card-text lead">This item above is in the shoes Categories which is sold at a preferable price.</p>
                <a href="#" class="btn btn-primary">Buy Now !</a>
              </div>
            </div>
            <div class="col-sm">
              <img class="card-img-top" src="../public/css/img/IMG_4784.jpg"  height="300" alt="item2">
              <div class="card-body">
                <h5 class="card-title">Item 2</h5>
                <p class="card-text lead">This item above is in the shoes Categories which is sold at a preferable price.</p>
                <a href="#" class="btn btn-primary">Buy Now !</a>
              </div>
            </div>
            <div class="col-sm">
              <img class="card-img-top" src="../public/css/img/IMG_4787.jpg"  height="300" alt="item2">
              <div class="card-body">
                <h5 class="card-title">Item 3</h5>
                <p class="card-text lead">This item above is in the shoes Categories which is sold at a preferable price.</p>
                <a href="#" class="btn btn-primary">Buy Now !</a>
              </div>
            </div>
          </div>
        </div>

        <hr class="mt-4 mb-3"/>
        <div class="container mb-4">
          <div class="row">
            <div class="col-md-6 mt-5">
              <img src="../public/css/img/IMG_4785.jpg" width="500" height="400" class="rounded d-block img-fluid">
            </div>
            <div class="col-md-6 mt-5">
              <p class="lead font-weight-light p-4"><b>Our group wanted to make a website specificly for customers that are looking to shop online during the pandemic. We created a market that sells all kind of equipment like from clothes, shoes, Electronics, etc. Contagion is designed to be diverse on the products we sell, which helps all to shop.</b></p>
            </div>
          </div>
      </div>
        

    </main>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    
    <script src="../public/js/bootstrap.min.js"></script>
  </body>
</html>